name: Build Simplipal

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Restore vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            build/vcpkg_installed
            vcpkg/downloads
          key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Configure CMake
        shell: powershell
        run: |
          cmake -B build `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows-static `
            -DVCPKG_FEATURE_FLAGS=manifests

      - name: Inspect JDBC headers
        shell: powershell
        run: |
          dir "${{ github.workspace }}\build\vcpkg_installed\x64-windows-static\include\jdbc" -Recurse

      - name: Build
        run: |
          cmake --build build --config Release
